name: Compile lab2
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Compile and run
        run: |
           cd lab2
           gcc uint1024.c char10.c -o main
           ./main- name: run file
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
            name: build
            path: lab2/main